
on: 
  push: 
jobs: 
  RunTTK: 
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Checkout TTK
        uses: actions/checkout@v2
        id: CheckoutTTK
        with: 
          repository: Azure/arm-ttk
          path: ttk
      - name: RunTTK
        id: RunTTK
        shell: pwsh
        run: |
          Import-Module ./ttk/arm-ttk/ -Force -PassThru | Out-Host
          Get-ChildItem -Recurse -Filter *.json |
              Where-Object Path -notlike '*ttk*' |
              Test-AzTemplate
          

