name: test-publish
on: 
- workflow_dispatch
- pull_request
- push
jobs: 
  TestAndPublish: 
    runs-on: ubuntu-latest
    env:
      ModulePath: .\arm-ttk\arm-ttk.psd1
      NuGetAPIKey: ${{ secrets.NuGetAPIKey }}
    steps:         
      - name: InstallPester
        shell: pwsh
        run: |
          $Parameters = @{}
          $Parameters.PesterMaxVersion = ${env:PesterMaxVersion}
          foreach ($k in @($parameters.Keys)) {
              if ([String]::IsNullOrEmpty($parameters[$k])) {
                  $parameters.Remove($k)
              }
          }
          Write-Host "::debug:: InstallPester $(@(foreach ($p in $Parameters.GetEnumerator()) {'-' + $p.Key + ' ' + $p.Value}) -join ' ')"
          & {<#
          .Synopsis
              Installs Pester
          .Description
              Installs Pester
          #>
          param(
          # The maximum pester version.  Defaults to 4.99.99.
          [string]
          $PesterMaxVersion = '4.99.99'
          )
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          Install-Module -Name Pester -Repository PSGallery -Force -Scope CurrentUser -MaximumVersion $PesterMaxVersion -SkipPublisherCheck -AllowClobber
          Import-Module Pester -Force -PassThru -MaximumVersion $PesterMaxVersion} @Parameters
      - name: Check out repository
        uses: actions/checkout@v2       
      - name: RunPester
        shell: pwsh
        run: |
          $Parameters = @{}
          $Parameters.ModulePath = ${env:ModulePath}
          $Parameters.PesterMaxVersion = ${env:PesterMaxVersion}
          foreach ($k in @($parameters.Keys)) {
              if ([String]::IsNullOrEmpty($parameters[$k])) {
                  $parameters.Remove($k)
              }
          }
          Write-Host "::debug:: RunPester $(@(foreach ($p in $Parameters.GetEnumerator()) {'-' + $p.Key + ' ' + $p.Value}) -join ' ')"
          & {<#
          .Synopsis
              Runs Pester
          .Description
              Runs Pester tests after importing a PowerShell module
          #>
          param(
          # The module path.  If not provided, will default to the second half of the repository ID.
          [string]
          $ModulePath,
          # The Pester max version.  By default, this is pinned to 4.99.99.
          [string]
          $PesterMaxVersion = '4.99.99'
          )
          
          $global:ErrorActionPreference = 'continue'
          $global:ProgressPreference    = 'silentlycontinue'
          
          $orgName, $moduleName = $env:GITHUB_REPOSITORY -split "/"
          if (-not $ModulePath) { $ModulePath = ".\$moduleName.psd1" }
          $importedPester = Import-Module Pester -Force -PassThru -MaximumVersion $PesterMaxVersion
          $importedModule = Import-Module $ModulePath -Force -PassThru
          $importedPester, $importedModule | Out-Host
          
          
          
          $result = 
              Invoke-Pester -PassThru -Verbose -OutputFile ".\$moduleName.TestResults.xml" -OutputFormat NUnitXml `
                  -CodeCoverage "$($importedModule | Split-Path)\*-*.ps1" -CodeCoverageOutputFile ".\$moduleName.Coverage.xml"
          
          "::set-output name=TotalCount::$($result.TotalCount)",
          "::set-output name=PassedCount::$($result.PassedCount)",
          "::set-output name=FailedCount::$($result.FailedCount)" | Out-Host
          if ($result.FailedCount -gt 0) {
              "::debug:: $($result.FailedCount) tests failed"
              foreach ($r in $result.TestResult) {
                  if (-not $r.Passed) {
                      "::error::$($r.describe, $r.context, $r.name -join ' ') $($r.FailureMessage)"
                  }
              }
              throw "::error:: $($result.FailedCount) tests failed"
          }
          } @Parameters
      - name: PublishTestResults
        if: ${{always()}}
        uses: actions/upload-artifact@v2
        with: 
          name: PesterResults
          path: '**.TestResults.xml' 
      - name: Publish module to PowerShell Gallery for master branch pushes only
        if: github.ref == 'refs/heads/master'
        shell: pwsh
        env:
          ModuleFolder: arm-ttk
        run: |
          $oldErrorActionPreference = $ErrorActionPreference
          $ErrorActionPreference = 'Continue'
          try {
              Publish-Module -Path "$env:GITHUB_WORKSPACE/$env:ModuleFolder" -NuGetAPIKey $env:NuGetAPIKey
              Write-Host -Object 'Module published to PowerShell Gallery'
              $ErrorActionPreference = $oldErrorActionPreference 
          }
          catch {
              if ($_.Exception.Message -ilike "*cannot be published as the current version*is already available in the repository*") {
                  "The latest version of module already exists in the repository."
                  continue
              }
              else {
                  $exitCode += 1
                  Write-Error $_
              }
          }
