on: workflow_dispatch
jobs: 
  UpdateTTKCache: 
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Log in with Azure
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
      - name: Update TTK Cache
        uses: Azure/powershell@v1
        with: 
          inlineScript: |
            Get-ChildItem -Recurse -Filter arm-ttk.psd1 | Import-Module -Name { $_.FullName} -Force -PassThru | Out-String
            Update-TTKCache
          azPSVersion: 3.1.0
